# Generated by Django 2.2.6 on 2019-10-18 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Yijie Yuan', max_length=15, verbose_name='author')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='pub_date')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('category', models.CharField(max_length=200, null=True, verbose_name='category')),
                ('sub_category', models.CharField(blank=True, max_length=200, verbose_name='sub_category')),
                ('body', models.TextField(verbose_name='body')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='likes')),
            ],
            options={
                'verbose_name': 'note',
            },
        ),
    ]
