# Generated by Django 2.2.6 on 2019-10-13 04:30

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=notes.models.user_directory_path)),
                ('upload_method', models.CharField(max_length=20, verbose_name='Upload Method')),
            ],
        ),
    ]
