# Generated by Django 2.2.6 on 2019-10-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='sup_category',
            field=models.CharField(blank=True, max_length=200, verbose_name='sub_category'),
        ),
    ]
