# Generated by Django 2.2.6 on 2019-10-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_file_upload_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='pub_date')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
