# Generated by Django 2.2.6 on 2019-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_sup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sup_category',
            field=models.CharField(blank=True, max_length=200, verbose_name='sup_category'),
        ),
    ]
