# Generated by Django 2.2.6 on 2019-10-14 18:56

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20191013_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
