# Generated by Django 2.2.6 on 2019-10-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20191014_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='Yijie Yuan', max_length=15, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
    ]
