# Generated by Django 2.2.6 on 2019-10-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20191015_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(max_length=200, null=True, verbose_name='category'),
        ),
    ]
