# Generated by Django 2.2.6 on 2019-10-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ahoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ahoice',
        ),
    ]
